// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Conntrack = newAsset("conntrack.c", "87f05f3e1c06274870a85e434f2fddd64f62bca57aa18bdf89c8aa93b7676e90")
