// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Conntrack = NewAsset("conntrack.c", "2e7c2cefa45d41cc4cd59f1d1860f846b9acdf63fbb5c0b2ede31aa4228f84b3")
