// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Conntrack = newAsset("conntrack.c", "0b60c8d6607df45879b4bb2b3efe875f81aed46c581e8dd5db8e05eef99309ca")
