// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Http = NewAsset("http.c", "f81ab351554d8b19bddf70165b4d76ce2259222ff0dd14b3059cd029394e2f8b")
