// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Http = newAsset("http.c", "3bdfdc83d5d14acf5675d537a67bddcb16b68383b295da29a188385582d88d42")
