// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Http = newAsset("http.c", "4e0650aebb7b2a4f1948ba80bfe8bafc125a2bf9980b24120d4aa4c089728175")
