// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Tracer = newAsset("tracer.c", "efe5d044271b6aa0a82320182484f737d36fcab07b3df8aa8af17c0be2310b78")
