// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Tracer = NewAsset("tracer.c", "b2510ee3a410003d7c589129eec7b7057b9c0e05fffb2ca0edbb45378b2d9ab7")
