// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Tracer = newAsset("tracer.c", "aa7c497fb8bab9ba65e788ab7f3d664f863c13b10e93805220ecba7605108858")
